# Try /Except

In [2]:
#the try bock you lets a block of code for error
#The except block lets you handle the error

In [3]:
a=1/0

ZeroDivisionError: division by zero

In [4]:
try:
    a=1/0
    print("yes")
except:
    print("I can't do that")

I can't do that


In [5]:
try:
    a=10/20
    print("yes i can")
except:
    print("no")

yes i can


# Libraries

In [6]:
#Python library is a collection of functions and methods that allows you to perform many actions without writing your code
#__init__.py

In [7]:
#Numpy
#Pandas 
#Matplotlib

# Numpy

In [8]:
#Numpy stands for Numerical python and is the core library for numerical and scientific computing.

In [9]:
import numpy as np

In [10]:
a=np.array([10,20,30,40])

In [11]:
a

array([10, 20, 30, 40])

In [12]:
a[1]

20

In [13]:
a[0]

10

In [15]:
a[3]

40

In [16]:
a.ndim

1

In [17]:
b=np.array([[1,2,3],[3,4,5],[4,5,6]])

In [18]:
b

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [19]:
b.ndim

2

In [20]:
c=np.array([[[1,2,3],[3,4,5],[5,6,7]]])

In [21]:
c

array([[[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]]])

In [22]:
c.ndim

3

# Zeros()

In [23]:
n1=np.zeros((10,20))

In [24]:
n1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

# Full

In [25]:
n2=np.full((8,8),10)

In [26]:
n2

array([[10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10]])

# arange()

In [27]:
n3=np.arange(10,20)

In [28]:
n3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [29]:
n4=np.arange(10,100)

In [30]:
n4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [31]:
n5=np.arange(10,100,5)

In [32]:
n5

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

# randint

In [33]:
n6=np.random.randint(1,100,5)

In [35]:
n6

array([22, 55, 58, 99, 64])

In [36]:
n6

array([22, 55, 58, 99, 64])

In [37]:
n6=np.random.randint(1,10,5)

In [38]:
n6

array([4, 3, 9, 7, 2])

In [39]:
n2

array([[10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10]])

In [40]:
b

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

# shape

In [41]:
b.shape

(3, 3)

# ndim

In [43]:
b.ndim

2

# itemsize

In [44]:
b.itemsize

4

# dtype

In [45]:
b.dtype

dtype('int32')

# size

In [46]:
b.size

9

# reshape

In [48]:
a=np.array([[1,2,3],[2,3,4]])

In [49]:
a.shape

(2, 3)

In [50]:
a.reshape(3,2)

array([[1, 2],
       [3, 2],
       [3, 4]])

# sum

In [52]:
b.sum(axis=0)#column

array([ 8, 11, 14])

In [53]:
b.sum(axis=1)#rows

array([ 6, 12, 15])

# std()

In [54]:
b.std()

1.4907119849998598

# dot

In [55]:
a=np.array([[[1,2,3],[3,2,0],[-1,2,0]]])

In [56]:
b=np.array([[[0,-1,-1],[1,2,3],[-1,1,-1]]])

In [57]:
a.dot(b)

array([[[[-1,  6,  2]],

        [[ 2,  1,  3]],

        [[ 2,  5,  7]]]])

# Joining Numpy array

In [58]:
a=np.array([10,20,30])

In [59]:
b=np.array([40,50,60])

# vstack

In [60]:
np.vstack((a,b))

array([[10, 20, 30],
       [40, 50, 60]])

# hstack

In [64]:
np.hstack((a,b))

array([10, 20, 30, 40, 50, 60])

# column_stack

In [65]:
np.column_stack((a,b))

array([[10, 40],
       [20, 50],
       [30, 60]])

# Intersection and diffrence

In [66]:
a

array([10, 20, 30])

In [67]:
b

array([40, 50, 60])

# intersection

In [68]:
np.intersect1d(a,b)

array([], dtype=int32)

In [69]:
a=np.array([1,2,3,4])

In [70]:
b=np.array([1,5,6,4])

In [71]:
np.intersect1d(a,b)

array([1, 4])

# setdiffrence

In [72]:
a

array([1, 2, 3, 4])

In [73]:
b

array([1, 5, 6, 4])

In [74]:
np.setdiff1d(a,b)

array([2, 3])

In [75]:
a,b

(array([1, 2, 3, 4]), array([1, 5, 6, 4]))

In [77]:
c=a+b

In [78]:
c

array([2, 7, 9, 8])

In [79]:
c/2

array([1. , 3.5, 4.5, 4. ])

In [80]:
c*2

array([ 4, 14, 18, 16])

In [81]:
c

array([2, 7, 9, 8])

# mean()

In [82]:
c.mean()

6.5

# std

In [86]:
np.std(c)

2.692582403567252

# median

In [87]:
np.median(c)

7.5

# Save and load the array

In [88]:
abc=np.array([10,20,30,40,50])

In [89]:
abc

array([10, 20, 30, 40, 50])

In [90]:
np.save("my_numpy",abc)