# Numpy

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])

In [10]:
b=np.array([1,2,3,4,5])

In [3]:
type(a)

numpy.ndarray

In [4]:
import array as arr

In [5]:
ab=arr.array("i",[1,2,3,4,5])

In [6]:
ab

array('i', [1, 2, 3, 4, 5])

In [8]:
type(ab)

array.array

In [20]:
ba=arr.array("i",[1,2,3,4,5])

In [21]:
ab*ba

TypeError: can't multiply sequence by non-int of type 'array.array'

In [12]:
a*b#o(1)

array([ 1,  4,  9, 16, 25])

In [22]:
for i in range(len(ab)):#o(n)
    print(ab[i]*ba[i])

1
4
9
16
25


# Zeros

In [23]:
a=np.zeros((10,10))

In [24]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# One

In [26]:
b=np.ones((10,10))

In [27]:
b

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# arange()

In [28]:
n1=np.arange(10,20)

In [29]:
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [30]:
n2=np.arange(10,50,5)

In [31]:
n2

array([10, 15, 20, 25, 30, 35, 40, 45])

# randint

In [36]:
n3=np.random.randint(1,100)

In [37]:
n3

30

In [40]:
n4=np.random.randint(1,100,5)

In [41]:
n4

array([53, 96, 76, 88, 50])

# Shape

In [46]:
n5=np.array([[1,2,3,4,5]])

In [47]:
n5.shape

(1, 5)

In [44]:
n6=np.array([[1,2,3,4],[1,2,3,4]])

In [45]:
n6.shape

(2, 4)

# ndim

In [48]:
n6.ndim

2

In [49]:
n7=np.array([[[1,2,3],[1,2,3],[1,2,3]]])

In [50]:
n7.ndim

3

# itemsize()

In [51]:
a=np.array([[1,2,3],[1,2,3]])

In [53]:
a.itemsize

4

# dtype

In [54]:
a.dtype

dtype('int32')

# size

In [55]:
a.size

6

# reshape

In [56]:
a

array([[1, 2, 3],
       [1, 2, 3]])

In [57]:
a.shape

(2, 3)

In [58]:
a.reshape(3,2)

array([[1, 2],
       [3, 1],
       [2, 3]])

In [59]:
a

array([[1, 2, 3],
       [1, 2, 3]])

# sum

In [60]:
a.sum()

12

In [61]:
a.sum(axis=1)

array([6, 6])

In [62]:
a.sum(axis=0)

array([2, 4, 6])

# dot

In [63]:
b=np.array([1,2,3])

In [65]:
c=np.array([1,2,3])

In [66]:
b.dot(c)

14

# eye

In [67]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Join Numpy array

In [68]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])

# vstack

In [69]:
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

# hstack

In [70]:
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

# column_stack

In [71]:
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

# Intersection and setdiffrence

In [72]:
f=np.array([10,20,30,40,50,60])
g=np.array([50,60,70,80,90,100])

In [74]:
np.intersect1d(f,g)

array([50, 60])

In [75]:
np.setdiff1d(f,g)

array([10, 20, 30, 40])

In [76]:
np.setdiff1d(g,f)

array([ 70,  80,  90, 100])

In [77]:
f

array([10, 20, 30, 40, 50, 60])

# std()

In [78]:
np.std(f)

17.07825127659933

# mean()

In [79]:
np.mean(f)

35.0

In [80]:
np.median(f)

35.0

In [81]:
len(dir(np))

600

# How to Save the array and how to load it ? 

In [82]:
d=np.array([1,2,3,4,5,6,7,8,9,10])

In [83]:
np.save("my_array",d)

# load array

In [85]:
g=np.load("my_array.npy")

In [86]:
g

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])