#Try/Except

In [90]:
try:
  print(1/0)
except Exception as e:
  print(e)
finally:
  print("I can't")

division by zero
I can't


In [91]:
try:
  import twilio
except Exception as e:
  print(e)

No module named 'twilio'


In [93]:
try:
  print(1/0)
except ZeroDivisionError as e:
  print(e)

division by zero


#Numpy

In [96]:
import numpy as np

In [97]:
a=np.array([1,2,3,4])

In [98]:
a

array([1, 2, 3, 4])

In [99]:
type(a)

numpy.ndarray

In [100]:
b=np.array([[1,2,3],[1,2,3]])

In [101]:
type(b)

numpy.ndarray

In [102]:
b

array([[1, 2, 3],
       [1, 2, 3]])

In [103]:
c=np.array([[[1,2,3],[1,2,3],[1,2,3]]])

In [104]:
type(c),c

(numpy.ndarray, array([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]]))

In [105]:
c.ndim

3

In [106]:
d=np.zeros((10,10))

In [107]:
d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [108]:
import array as arr

In [115]:
d=arr.array("i",[1,2,3,4])

In [117]:
e=arr.array("i",[1,2,3,4])

In [111]:
a*b

TypeError: ignored

In [113]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])

In [114]:
a*b

array([ 1,  4,  9, 16])

In [118]:
d,e

(array('i', [1, 2, 3, 4]), array('i', [1, 2, 3, 4]))

In [125]:
for i in range(4):
  print(d[i]*e[i])

1
4
9
16
